linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - exportloopref
    - gofmt
    - goimports
    - golint
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck

issues:
  include:
    - EXC0002 # disable excluding of issues about comments from golint
