.git
.github
.idea
.vscode
.env
.env.*
.netrc
.npmrc
.pypirc
.aws/
.docker/
.config/gcloud/
*.pem
*.key
*.p12

AGENTS.md
CONTRIBUTING.md
README.md
design.md

integration_tests/
examples/

vendor/
bin/
coverage/
dist/
tmp/
.trees/
*.log
*.out
*.prof
*.test
