name: Compatibility Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  tidb-compatibility:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21.0"

    - name: Checkout Client-Go
      uses: actions/checkout@v2
      with:
        path: client-go
    
    - name: Checkout TiDB
      uses: actions/checkout@v2
      with:
        repository: pingcap/tidb
        path: tidb

    - name: Check build
      run: |
        go mod edit -replace=github.com/tikv/client-go/v2=../client-go
        go mod tidy
        make server
      working-directory: tidb

    - name: Checkout go-ycsb
      uses: actions/checkout@v2
      with:
        repository: pingcap/go-ycsb
        path: go-ycsb

    - name: Check build
      run: |
        go mod edit -replace=github.com/tikv/client-go/v2=../client-go
        go mod tidy
        go build cmd/go-ycsb/*
      working-directory: go-ycsb
